# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 26bf0e707943cf37666f40f923cf3a1b94850bd1d3282d4299843f0193ab06a78a7187da99415ef559c822e4e7879f594be8bbbfc1ef7f538ad31593d4a27c0a

test:
  secret_key_base: 9fcad384e0e4cd6abfd7a98db98cb82170cdae646232e885a48408e3b7e4e371019e0ca9bba45764d267c0d901cb14a59d622adafc9a0fcfe71b1695b5e29639

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
